// asd.res - created with RESGen v2.0.3.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (9):
decals.wad
extension.wad
halflife.wad
jp_dev.wad
last.wad
models/player/ugandan_knuckles/ugandan_knuckles.mdl
nw.wad
opfor.wad
scopfor.wad
models/player/ugandaknacle/ugandaknacle.mdl
models/player/ugandaknacle/ugandaknacle.bmp
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
sprites/hl_weapons/weapon_hl357.txt
models/hl/p_357.mdl
models/hl/v_357.mdl
models/hl/w_357.mdl
models/hl/w_357t.mdl
sound/hl/weapons/357_reload1.wav
sound/hl/weapons/357_shot1.wav
sound/hl/weapons/357_shot2.wav
sound/gta2/wasted.wav
models/player/TFC_engineer_HD/TFC_engineer_HD.mdl
models/player/TFC_engineer_HD/TFC_engineer_HD.bmp
models/player/TFC_demo_HD/TFC_demo_HD.mdl
models/player/TFC_demo_HD/TFC_demo_HD.bmp
models/player/TFC_hvyweapon_HD/TFC_hvyweapon_HD.mdl
models/player/TFC_hvyweapon_HD/TFC_hvyweapon_HD.bmp
models/player/TFC_Medic_HD/TFC_Medic_HD.mdl
models/player/TFC_Medic_HD/TFC_Medic_HD.bmp
models/player/TFC_pyro_HD/TFC_pyro_HD.mdl
models/player/TFC_pyro_HD/TFC_pyro_HD.bmp
models/player/TFC_scout_HD/TFC_scout_HD.mdl
models/player/TFC_scout_HD/TFC_scout_HD.bmp
models/player/TFC_sniper_HD/TFC_sniper_HD.mdl
models/player/TFC_sniper_HD/TFC_sniper_HD.bmp
models/player/TFC_soldier_HD/TFC_soldier_HD.mdl
models/player/TFC_soldier_HD/TFC_soldier_HD.bmp
models/player/TFC_spy_HD/TFC_spy_HD.mdl
models/player/TFC_spy_HD/TFC_spy_HD.bmp
models/player/ta_flanker/ta_flanker.bmp
models/player/ta_assault/ta_assault.bmp
models/player/ta_marine/ta_marine.bmp
models/player/ta_operative/ta_operative.bmp
models/player/ta_research/ta_research.bmp
models/player/ta_support/ta_support.bmp
models/player/ta_tank/ta_tank.bmp
models/player/HS_Chocolate/HS_Chocolate.mdl
models/player/HS_Chocolate/HS_Chocolate.bmp
models/player/HS_Mikk/Mikk.mdl
models/player/HS_Mikk/Mikk.bmp
models/player/HS_Onix047/Onix047.mdl
models/player/HS_Onix047/Onix047.bmp
models/player/epsilon_HS/epsilon_HS.mdl
models/player/epsilon_HS/epsilon_HS.bmp
models/player/HS_O4/HS_O4.mdl
models/player/HS_O4/HS_O4.bmp
models/player/HS_O4EPS/HS_O4EPS.mdl
models/player/HS_O4EPS/HS_O4EPS.bmp
models/player/HS_O4CHO/HS_O4CHO.mdl
models/player/HS_O4CHO/HS_O4CHO.bmp
models/player/HS_O4JEB/HS_O4JEB.mdl
models/player/HS_O4JEB/HS_O4JEB.bmp
models/player/HS_O4BUC/HS_O4BUC.mdl
models/player/HS_O4BUC/HS_O4BUC.bmp
models/player/HS_O4BIG/HS_O4BIG.mdl
models/player/HS_O4BIG/HS_O4BIG.bmp